/**
 * CreateCircleService - Handles creating a circle flow
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:3001";

export interface CreateCircleParams {
    circlePurpose: string;
    contributionFrequency: "weekly" | "monthly";
    contributionAmount: number; // satoshis
    maxMembers: number;
    creatorPubkey: string; // hex-encoded
    fundingUtxo: string;
    fundingUtxoValue: number;
    changeAddress: string;
}

export interface CreateCircleResult {
    psbt: string;
    spellYaml: string;
    circleId?: string;
    txid?: string; // Transaction ID if backend broadcast successfully
}

export class CreateCircleService {
    /**
     * Build create spell and generate PSBT
     */
    async prepareCreateCircle(
        params: CreateCircleParams
    ): Promise<CreateCircleResult> {
        // Calculate round duration based on frequency
        const roundDuration =
            params.contributionFrequency === "weekly"
                ? 7 * 24 * 60 * 60 // 7 days in seconds
                : 30 * 24 * 60 * 60; // 30 days in seconds

        const appBin = "./target/wasm32-wasip1/release/charmcircle.wasm";

        // Calculate app_id (will be generated by backend from circle_id)
        // For now, we'll let backend generate it

        // Build parameters for create spell
        // Note: Backend will generate circle_id and create state via serialize_state
        const spellParams: Record<string, string> = {
            contribution_per_round: params.contributionAmount.toString(),
            round_duration: roundDuration.toString(),
            created_at_timestamp: Math.floor(Date.now() / 1000).toString(),
            creator_pubkey_hex: params.creatorPubkey,
            purpose: params.circlePurpose, // Circle name/purpose
            max_members: params.maxMembers.toString(), // Maximum members
            // These will be filled by backend or need to be provided:
            circle_address: params.changeAddress, // Use change address for circle output
            in_utxo_0: params.fundingUtxo || "", // Funding UTXO
            // Backend will generate:
            // - circle_id (via crypto.randomBytes)
            // - circle_state_serialized (via serialize_state)
            // - app_id (calculated from in_utxo_0)
            // - app_vk (from charms app vk)
        };

        // Call backend to build and prove spell
        const response = await fetch(
            `${API_BASE_URL}/api/spells/build-and-prove`,
            {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    templateName: "create-circle",
                    parameters: spellParams,
                    appBin,
                    prevTxs: "", // No previous transactions for create
                    fundingUtxo: params.fundingUtxo,
                    fundingUtxoValue: params.fundingUtxoValue,
                    changeAddress: params.changeAddress,
                }),
            }
        );

        if (!response.ok) {
            const error = await response.json();
            throw new Error(
                error.error?.message || "Failed to prepare create transaction"
            );
        }

        const data = await response.json();
        return {
            psbt: data.data.proveResult.psbt,
            spellYaml: data.data.spellYaml,
            circleId: data.data.circleId, // If backend returns it
            txid: data.data.txid, // Transaction ID if backend broadcast it
        };
    }
}
